domain_whitelists = {
	"api.haxe.org": ["https://api.haxe.org/"],
	"api.qunitjs.com": ["https://qunitjs.com/api/"],
	"babeljs.io": ["https://babeljs.io/docs/"],
	"bazel.build": ["https://bazel.build/start/", "https://bazel.build/docs/", "https://bazel.build/reference/"],
	"bluebirdjs.com": ["http://bluebirdjs.com/docs/"],
	"bower.io": ["https://bower.io/"],
	"cfdocs.org": ["https://cfdocs.org/"],
	"clojuredocs.org": ["https://clojuredocs.org/"],
	"clojure.org": ["https://clojure.org/"],
	"codecept.io": ["https://codecept.io/"],
	"codeception.com": ["https://codeception.com/docs/", "https://codeception.com/docs/Introduction"],
	"codeigniter.com": ["https://codeigniter.com/user_guide/"],
	"cran.r-project.org": ["https://cran.r-project.org/doc/manuals/"],
	"crystal-lang.org": ["https://crystal-lang.org/reference/1.14/"],
	"css-tricks.com": ["https://css-tricks.com/category/articles/"],
	"dart.dev": ["https://dart.dev/"],
	"developer.apple.com": ["https://developer.apple.com/"],
	"developer.mozilla.org": ["https://developer.mozilla.org/en-US/docs/Web/"],
	"dev.mysql.com": ["https://dev.mysql.com/doc/"],
	"doc.rust-lang.org": ["https://doc.rust-lang.org/std/"],
	"docs.astro.build": ["https://docs.astro.build/en/getting-started/", "https://docs.astro.build/en/"],
	"docs.brew.sh": ["https://docs.brew.sh/"],
	"docs.chef.io": ["https://docs.chef.io/"],
	"docs.cypress.io": ["https://docs.cypress.io/app/get-started/why-cypress", "https://docs.cypress.io/app/"],
	"docs.influxdata.com": ["https://docs.influxdata.com/"],
	"docs.julialang.org": ["https://docs.julialang.org/en/v1/"],
	"docs.python.org": ["https://docs.python.org/2/", "https://docs.python.org/3/"],
	"docs.ruby-lang.org": ["https://docs.ruby-lang.org/en/master/", "https://docs.ruby-lang.org/capi/en/master/"],
	"docs.saltproject.io": ["https://docs.saltproject.io/en/latest/contents.html", "https://docs.saltproject.io/en/latest/"],
	"docs.wagtail.org": ["https://docs.wagtail.org/en/stable/"],
	"doctrine-project.org": ["https://www.doctrine-project.org/"],
	"eigen.tuxfamily.org": ["https://eigen.tuxfamily.org/dox/"],
	"en.cppreference.com": ["https://en.cppreference.com/w/c", "https://en.cppreference.com/w/cpp"],
	"erights.org": ["http://erights.org/elang/"],
	"erlang.org": ["https://www.erlang.org/doc/readme.html", "https://www.erlang.org/doc/"],
	"esbuild.github.io": ["https://esbuild.github.io/"],
	"eslint.org": ["https://eslint.org/docs/latest/"],
	"expressjs.com": ["https://expressjs.com/"],
	"fastapi.tiangolo.com": ["https://fastapi.tiangolo.com/"],
	"flow.org": ["https://flow.org/en/docs/"],
	"fortran90.org": ["https://www.fortran90.org/"],
	"fsharp.org": ["https://fsharp.org/"],
	"getbootstrap.com": ["https://getbootstrap.com/docs/5.3/getting-started/introduction/", "https://getbootstrap.com/docs/5.3/"],
	"getcomposer.org": ["https://getcomposer.org/doc/"],
	"git-scm.com": ["https://git-scm.com/doc"],
	"gnucobol.sourceforge.io": ["https://gnucobol.sourceforge.io/"],
	"go.dev": ["https://go.dev/doc/"],
	"graphite.readthedocs.io": ["https://graphite.readthedocs.io/en/stable/"],
	"groovy-lang.org": ["https://groovy-lang.org/"],
	"gruntjs.com": ["https://gruntjs.com/"],
	"handlebarsjs.com": ["https://handlebarsjs.com/"],
	"httpd.apache.org": ["https://httpd.apache.org/docs/2.4/"],
	"i3wm.org": ["https://i3wm.org/"],
	"jasmine.github.io": ["https://jasmine.github.io/"],
	"javascript.info": ["https://javascript.info/"],
	"jekyllrb.com": ["https://jekyllrb.com/docs/"],
	"jsdoc.app": ["https://jsdoc.app/"],
	"knockoutjs.com": ["https://knockoutjs.com/"],
	"laravel.com": ["https://laravel.com/docs/11.x/"],
	"latexref.xyz": ["https://latexref.xyz/"],
	"learn.microsoft.com": ["https://learn.microsoft.com/en-us/dotnet/"],
	"man7.org": ["https://man7.org/linux/man-pages/"],
	"mariadb.com": ["https://mariadb.com/docs/server/architecture/", "https://mariadb.com/docs/server/ref/mdb/"],
	"mongoosejs.com": ["https://mongoosejs.com/docs/"],
	"next.router.vuejs.org": ["https://router.vuejs.org/guide/", "https://router.vuejs.org/api/"],
	"nginx.org": ["https://nginx.org/en/docs/"],
	"nim-lang.org": ["https://nim-lang.org/documentation.html", "https://nim-lang.org/docs/manual.html", "https://nim-lang.org/docs/"],
	"nodejs.org": ["https://nodejs.org/docs/latest/api/"],
	"ocaml.org": ["https://ocaml.org/docs"],
	"odin-lang.org": ["https://odin-lang.org/docs/"],
	"opentsdb.net": ["https://opentsdb.net/docs/build/html/"],
	"perldoc.perl.org": ["https://perldoc.perl.org/"],
	"php.net": ["https://www.php.net/manual/en/"],
	"playwright.dev": ["https://playwright.dev/docs/intro", "https://playwright.dev/docs/"],
	"postgresql.org": ["https://www.postgresql.org/docs/current/"],
	"prettier.io": ["https://prettier.io/docs/en/"],
	"pugjs.org": ["https://pugjs.org/api/getting-started.html", "https://pugjs.org/"],
	"pytorch.org": ["https://pytorch.org/docs/stable/", "https://pytorch.org/audio/stable/index.html", "https://pytorch.org/torchtune/stable/", "https://pytorch.org/torcharrow/beta/", "https://pytorch.org/data/beta/", "https://pytorch.org/torchrec/", "https://pytorch.org/serve/", "https://pytorch.org/xla/release/2.1/", "https://pytorch.org/rl/stable/", "https://pytorch.org/tensordict/stable/", "https://pytorch.org/text/stable/", "https://pytorch.org/executorch/stable/"],
	"react-bootstrap.github.io": ["https://react-bootstrap.github.io/docs/getting-started/introduction", "https://react-bootstrap.github.io/docs/"],
	"reactivex.io": ["https://reactivex.io/"],
	"reactjs.org": ["https://react.dev/reference/react", "https://react.dev/reference/"],
	"reactnative.dev": ["https://reactnative.dev/docs/getting-started", "https://reactnative.dev/docs/"],
	"redis.io": ["https://redis.io/docs/latest/develop/"],
	"redux.js.org": ["https://redux.js.org/"],
	"requirejs.org": ["https://requirejs.org/"],
	"rethinkdb.com": ["https://rethinkdb.com/docs/", "https://rethinkdb.com/api/javascript/", "https://rethinkdb.com/api/python/", "https://rethinkdb.com/api/ruby/", "https://rethinkdb.com/api/java/"],
	"ruby-doc.org": ["https://ruby-doc.org/3.4.1/"],
	"rxjs.dev": ["https://rxjs.dev/guide/operators", "https://rxjs.dev/guide/", "https://rxjs.dev/api/"],
	"sass-lang.com": ["https://sass-lang.com/documentation/"],
	"scikit-image.org": ["https://scikit-image.org/docs/stable/"],
	"scikit-learn.org": ["https://scikit-learn.org/stable/"],
	"spring.io": ["https://spring.io/guides"],
	"sqlite.org": ["https://sqlite.org/c3ref/intro.html", "https://sqlite.org/c3ref/"],
	"stdlib.ponylang.io": ["https://stdlib.ponylang.io"],
	"svelte.dev": ["https://svelte.dev/docs/kit/introduction", "https://svelte.dev/docs/kit/", "https://svelte.dev/docs/svelte/overview", "https://svelte.dev/docs/svelte/"],
	"tailwindcss.com": ["https://tailwindcss.com/docs/installation", "https://tailwindcss.com/docs/"],
	"twig.symfony.com": ["https://twig.symfony.com/doc/3.x/"],
	"typescriptlang.org": ["https://www.typescriptlang.org/docs/"],
	"vitest.dev": ["https://vitest.dev/guide/", "https://vitest.dev/api/"],
	"vuejs.org": ["https://vuejs.org/guide/introduction.html", "https://vuejs.org/guide/", "https://vuejs.org/api/"],
	"webpack.js.org": ["https://webpack.js.org/concepts/"],
	"www.chaijs.com": ["https://www.chaijs.com/"],
	"www.electronjs.org": ["https://www.electronjs.org/docs/latest/"],
	"www.gnu.org": ["https://www.gnu.org/"],
	"www.hammerspoon.org": ["https://www.hammerspoon.org/"],
	"www.php.net": ["https://www.php.net/manual/en/"],
	"www.pygame.org": ["https://www.pygame.org/docs/"],
	"www.statsmodels.org": ["https://www.statsmodels.org/stable/"],
	"www.swift.org": ["https://www.swift.org/documentation/"],
	"www.tcl.tk": ["https://www.tcl.tk/man/tcl8.6.13/"],
	"www.yiiframework.com": ["https://www.yiiframework.com/doc/guide/2.0/en", "https://www.yiiframework.com/doc/"],
	"yarnpkg.com": ["https://yarnpkg.com/"],
}
domain_blacklists = {
	"api.haxe.org": ["https://api.haxe.org/v/"],
	"developer.apple.com": ["https://developer.apple.com/cn/", "https://developer.apple.com/jp/", "https://developer.apple.com/kr/", "https://developer.apple.com/videos/", "https://developer.apple.com/library/archive/", "https://developer.apple.com/forums/"],
	"learn.microsoft.com": ["https://learn.microsoft.com/en-us/dotnet/framework/", "https://learn.microsoft.com/en-us/dotnet/api/"],
	"man7.org": ["https://man7.org/linux/man-pages/man3/"],
	"mariadb.com": ["https://mariadb.com/docs/server/ref/mdb/error-codes/"],
	"perldoc.perl.org": ["https://perldoc.perl.org/5."],
	"www.gnu.org": ["https://www.gnu.org/server/", "https://www.gnu.org/software/"],
}
